### ISSUE TITLE
Outdated URLs to Black GitHub project in a blog post

### ISSUE THREAD

**Issue by 1inuxoid** [ljvmiranda921/ljvmiranda921.github.io#292]
[This blog post](https://github.com/ljvmiranda921/ljvmiranda921.github.io/blob/master/notebook/_posts/2018-06-21-precommits-using-black-and-flake8.md) mentions an updated URL to [Black](https://github.com/psf/black) in the **Changelog** but the URL itself is still outdated.

**Comment by 1inuxoid** [comment]
Apologies, I forgot to offer my gratitude for a very practical post first 😅

**Comment by ljvmiranda921** [comment]
Oh thanks for pointing it out!
